import time
print('\r▁', end='')
time.sleep(0.5)
print('\r▁▂', end='')
time.sleep(0.5)
print('\r▁▂▄', end='')
time.sleep(0.5)
print('\r▁▂▄▅', end='')
time.sleep(0.5)
print('\r▁▂▄▅▆', end='')
time.sleep(0.5)
print('\r▁▂▄▅▆▇', end='')
time.sleep(0.5)
print('\r▁▂▄▅▆▇█', end='')
time.sleep(0.5)

#time.sleep(0.5)
#print('\r', end='')
#time.sleep(0.5)
#print('\r', end='')
#time.sleep(0.5)
#print('\r', end='')
#time.sleep(0.5)
#print('\r', end='')
#time.sleep(0.5)